version: '3'

services:
  elasticsearch:
    container_name: jobda-elasticsearch
    build:
      context: ./elasticsearch
      dockerfile: elasticsearch-nori.Dockerfile

    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true

    ulimits:
      memlock:
        soft: -1
        hard: -1

    ports:
      - "9200:9200"

    volumes:
      - es-data:/usr/share/elasticsearch/data

    networks:
      - jobda-network

volumes:
  es-data:

networks:
  jobda-network:
    driver: bridge