services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobda-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}    #  메일 계정
      MAIL_PASSWORD: ${MAIL_PASSWORD}    #  메일 앱 비밀번호
      JWT_SECRET: ${JWT_SECRET}
      TZ: Asia/Seoul
    restart: on-failure
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  db:
    image: mysql:8
    container_name: jobda-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  redis:
    image: redis:7.2
    container_name: jobda-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
  mysql-data: