version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: jobda-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - jobda-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: jobda-prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    volumes:
      # prometheus.yml은 환경별로 교체해서 사용
      # 로컬: prometheus-local.yml → prometheus-prod.yml
      # 배포: prometheus-prod.yml  → prometheus-prod.yml
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - jobda-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.3
    container_name: jobda-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - jobda-net
    restart: unless-stopped

volumes:
  redis-data:
  grafana-data:

networks:
  jobda-net:
    external: true